name: Package and Release

on:
  push:
  pull_request:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pack Plugin
      run: |
        python -m mcdreforged pack -o ./package

    - uses: actions/upload-artifact@v3
      with:
        name: Blive_danmaku distribution for ${{ github.sha }}
        path: package/

    - uses: actions/setup-node@v3
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        node-version: 16.x

    - run: npx changelogithub
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload binaries to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        file: package/*.pyz
